### PR TITLE
Add ESLint with airbnb rules, fix all files

### PR DESCRIPTION
**Pull request by jbinto**
This PR

* upgrades all eslint packages, adds several new ones
* adds a `.babelrc` so non-Webpack programs (e.g. eslint) can parse our code
* adds `lint` and `lint-fail-fast` npm scripts. The former always returns true (so you don't get a massive npm error log when linting fails), the latter is intended for running on CI so the build will fail if linting fails.

All rules in the Airbnb set are followed, with the following exceptions:

* [semi](http://eslint.org/docs/rules/semi) which we have configured to enforce NO semicolons
* [eqeqeq](http://eslint.org/docs/rules/eqeqeq) which we have configured to allow `==` only when comparing to `null`, and require `===` everywhere else.

The following is a subset of those rules that actually required changes in this PR, roughly in the order they appear in the diff:

* [react/prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md)
* [prefer-const](http://eslint.org/docs/rules/prefer-const)
* [guard-for-in](http://eslint.org/docs/rules/guard-for-in) - **NOTE:** rather than use the ugly `if ({}.hasOwnProperty.call(foo, key)) {` call on every `for..in` loop, we should just re-write these to be more functional (map/filter/reduce). In at least one case I just suppressed the rule, should probably go back and fix this. 
* [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing)
* [quotes](http://eslint.org/docs/rules/quotes) (single)
* [callback-return](http://eslint.org/docs/rules/callback-return)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops)
* [no-else-return](http://eslint.org/docs/rules/no-else-return)
* [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
* [react/display-name](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md)
* [max-len](http://eslint.org/docs/rules/max-len)
* [react/sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md)
* [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren)
* [no-param-reassign](http://eslint.org/docs/rules/no-param-reassign)
* [brace-style](http://eslint.org/docs/rules/brace-style)
* [object-shorthand](http://eslint.org/docs/rules/object-shorthand)
* [func-names](http://eslint.org/docs/rules/func-names)
* [no-throw-literal](http://eslint.org/docs/rules/no-throw-literal)

Other stylistic changes not forced by eslint:

* `delegates_public_functions.js` and `higher_order_component.js` were rewritten to use ES6 modules and nested arrow functions
* Refactored `util.js` to not have a top-level `util` object, that gets self-referenced (e.g. `util.foo` calls `util.bar`) -- instead just make every util top level and export them directly

### CODE REVIEW

**Comment by jbinto** [comment]
Note: Don't merge without looking into this

[In at least one case](https://github.com/frig-js/frig/compare/develop...jbinto:eslint?expand=1#diff-2f7a83d6e98760f5c2ae4efe456c0225L26) I mistakenly converted this to a map on an object (rather than it's keys). Please make sure to double check these.

**Comment by jbinto** [comment]
Same mistake here:

https://github.com/frig-js/frig/pull/45/files#diff-bad83f5cdcf5e0707c6319a97040e015L95

**Comment by jbinto** [comment]
This is fixed now.

**Comment by jbinto** [comment]
c535210: Cherry picked a fix for a typo in `.babelrc`

**Comment by SpiritBreaker226** [comment]
@jbinto Before this can be merge, there are tasks that need to be completed:
 - [ ] Update your version of Frig
 - [ ] Rerun the lint because you update the lint rules after going throw the components and now the componets are no longer following the updated rules
 - [ ] add back `babel-plugin-transform-decorators-legacy` NPM package as it was remove at some point

**Comment by jbinto** [comment]
OK, both done.

**Comment by SpiritBreaker226** [comment]
👍

**Pull request merged**
