### PR TITLE
Fix Saved List Use Component Name Instead Value

### PR DESCRIPTION
**Pull request by SpiritBreaker226**
Fix the saved list use to the component name instead of its value because for switches and checkboxes they can return a boolean value  which could turn off the saved label when they change. 

Also, fix a nested fieldset warning for its saved list. It was using the wrong props type.

### CODE REVIEW

**Comment by D1plo1d** [comment]
But if it's an array how do you deal with nesting?

**Comment by SpiritBreaker226** [comment]
Same way as how data is being entered into the nested field by array of objects.

**Comment by SpiritBreaker226** [comment]
After looking again it now no longer works :disappointed: I will remove that commit.

**Comment by D1plo1d** [comment]
maybe a `modifiedFields` object tree where each leaf contains `true` is the best option here?

**Comment by SpiritBreaker226** [comment]
When adding hasOwnProperty to nested field, in the form.js. It should have been sending down the array of objects instead of a boolean value to the nested field. This is why it was not showing up. 

However, I did find an error similar to the form, in the nested field, where a boolean value can control the saved label. I am going to fix this and push up a that commit.

**Comment by SpiritBreaker226** [comment]
I have made the changes and do some testing it looks like everything is good to go.

**Pull request closed without merging**
