### PR TITLE
Initial setup of mocha/chai/jsdom testing infrastructure

### PR DESCRIPTION
**Pull request by jbinto**
This PR

* Removes previous test files
* Adds devDependencies `chai`, `mocha`, `enzyme`, `dirty-chai`, `jsdom`
* Adds `react-dom` to peerDependencies and devDependencies
* Fixes bug in `src/higher_order_components/higher_order_component.js`, was missing an arrow function
* Adds npm scripts `test` and `test:watch`
* Adds `test/test_helper.js` for setting up mocha with jsdom
* **Adds tests** for:
  * `<Form/>` (including `AbstractForm`)
  * `src/util.js`
  * `src/validations.js`

Refactorings:

* **BREAKING**: In `src/index.js`, do not `export default` an object, rather use only named exports with no default export. 
  * This means `Frig.defaultTheme()` will no longer work (consumers would have to `import { defaultTheme } from 'frig'`. 
  * It's probably worth considering special-casing just that one import, so we can retain the old syntax. 
  * *([Read this for justification, ^F for "Why do we need named exports?"](http://www.2ality.com/2014/09/es6-modules-final.html))*

* In `src/components/abstract_form.js`, remove useless `_data()` method

* In `src/higher_order_components/errors_normalizer.js`, remove dead code from`_errors()`

* Change `src/validations.js` from CommonJS to ES6 module

* Add names to all anonymous classes

* Remove all dead code from `src/util.js` (most of the file!)

### CODE REVIEW

**Comment by jbinto** [comment]
It's probably worth adding a CircleCI config to this so we can see the tests pass/fail.

**Comment by SpiritBreaker226** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;41Q9iG2R&#x2F;1264-frig-complete-tests-and-refactoring"> Frig: complete tests and refactoring</a>

**Comment by jbinto** [comment]
Figured out how to get coverage working reliably again. See detailed commit message here: 
https://github.com/frig-js/frig/pull/47/commits/79a4e3bf44b2902e49dd1a60a31b85b26743a6b3

**Comment by SpiritBreaker226** [comment]
@jbinto could you split this pull request into three Testing, Circle CI and Code Coverage?

**Comment by jbinto** [comment]
OK, I reset this branch to end at the last unit test, and will add separate PRs for CircleCI/code coverage.

**Comment by SpiritBreaker226** [comment]
👍

**Pull request merged**
